// react-app/src/Pages/Login.jsx
import { useState } from "react";
import "../Pages/Login.css";
function Login() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const handleUsernameChange = (event) => {
    setUsername(event.target.value);
  };

  const handlePasswordChange = (event) => {
    setPassword(event.target.value);
  };

  const handleSubmit = (event) => {
    event.preventDefault();
    if (username.length === 0 || password.length === 0) {
      setError("Ошибка");
    } else {
      setError("Ok");
    }
  };

  return (
    <form className="form" onSubmit={handleSubmit}>
      <label>
        Логин:
        <input
          placeholder="Введите логин"
          value={username}
          onChange={handleUsernameChange}
        />
      </label>
      <label>
        Пароль:
        <input
          placeholder="Введите пароль"
          value={password}
          onChange={handlePasswordChange}
        />
      </label>
      <button type="submit" className="signInButton">
        Войти
      </button>
      {error && <div style={{ color: "red" }}>{error}</div>}
    </form>
  );
}

export default Login;

// angular-app/src/app/login/login.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent {
  username = '';
  password = '';
  error = '';

  constructor() {}

  validation() {
    if (this.username.length === 0 || this.password.length === 0) {
      console.log('false');
      this.error = 'Error';
    } else {
      console.log('true');
      this.error = 'ok';
    }
  }
}

<form>
  <label for="username"
    >Логин:<input
      [(ngModel)]="username"
      placeholder="Введите логин"
      [ngModelOptions]="{ standalone: true }"
  /></label>
  <label for="password"
    >Пароль:
    <input
      [(ngModel)]="password"
      placeholder="Введите пароль"
      [ngModelOptions]="{ standalone: true }"
  /></label>
  <button type="submit" (click)="validation()">Войти</button>
  <div *ngIf="error" style="color: red">{{ error }}</div>
</form>
